### ISSUE TITLE
Provider com.bea.xml.stream.EventFactory not found

### ISSUE THREAD

**Issue by AhmadIzaz** [SUPERCILEX/poi-android#10]
I want to know the count of pages of excel sheet and I am trying to do this by using the below code but I am getting an exception.

public static int getExcelSheetCount(String filePath) {
        int sheetCount = 0;
        OPCPackage myFileSystem = null;
        try {
            // Creating Input Stream
            File file = new File(filePath);
            FileInputStream myInput = new FileInputStream(file);

            // Create a POIFSFileSystem object
            myFileSystem = OPCPackage.open(file);

            // Create a workbook using the File System
            XSSFWorkbook myWorkBook = new XSSFWorkbook(myFileSystem);

            sheetCount = myWorkBook.getNumberOfSheets();

            /*// Get the first sheet from workbook
            HSSFSheet mySheet = myWorkBook.getSheetAt(0);

            *//** We now need something to iterate through the cells.**//*
            Iterator<Row> rowIter = mySheet.rowIterator();

            while(rowIter.hasNext()){
                HSSFRow myRow = (HSSFRow) rowIter.next();
                Iterator<Cell> cellIter = myRow.cellIterator();
                while(cellIter.hasNext()){
                    HSSFCell myCell = (HSSFCell) cellIter.next();
                    Log.w("FileUtils", "Cell Value: " +  myCell.toString());
                    Toast.makeText(context, "cell Value: " + myCell.toString(), Toast.LENGTH_SHORT).show();
                }
            }*/
            myFileSystem.close();
        } catch (Exception e) {
            e.printStackTrace();
            try {
                if (myFileSystem != null)
                    myFileSystem.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

        return sheetCount;
    }

**Comment by SUPERCILEX** [comment]
See https://github.com/SUPERCILEX/poi-android/issues/5

**Comment by AhmadIzaz** [comment]
@SUPERCILEX   can you let us know where we have to add these lines System.setProperty which you mentioned in #5.
In Gradle ??

**Comment by AhmadIzaz** [comment]
I have put these lines System.setProperty in Android Application class and this seems to be working with that yet.
