### ISSUE TITLE
Problem to write xlsx files.

### ISSUE THREAD

**Issue by joao-moniz** [SUPERCILEX/poi-android#2]
When I try to run 

> XSSFWorkbook workbook = new XSSFWorkbook(); 

I get the error

`java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection"`

**Comment by SUPERCILEX** [comment]
That class doesn't look related (it's part of the support library). I'm guessing you didn't [correctly enable multidex](https://developer.android.com/studio/build/multidex#mdex-pre-l).
