### ISSUE TITLE
org.apache.poi.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.EventFactory not found

### ISSUE THREAD

**Issue by anta40** [SUPERCILEX/poi-android#5]
Demo code: https://github.com/anta40/StockChecker

My app always crashes when loading XLSX files, seems like because of "org.apache.poi.javax.xml.stream.FactoryConfigurationError: Provider com.bea.xml.stream.EventFactory not found"

This is the content of build.gradle:

> android {
>     compileSdkVersion 28
>     defaultConfig {
>         applicationId "com.anta40.app.stockchecker"
>         minSdkVersion 15
>         targetSdkVersion 28
>         multiDexEnabled true
>         versionCode 1
>         versionName "1.0"
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>     }
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> dependencies {
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation 'com.android.support:appcompat-v7:28.0.0'
>     implementation 'com.android.support:multidex:1.0.3'
>     implementation 'com.android.support.constraint:constraint-layout:1.1.3'
>     implementation 'com.github.SUPERCILEX.poi-android:poi:3.17'
>     implementation 'com.github.angads25:filepicker:1.1.1'
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'com.android.support.test:runner:1.0.2'
>     androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
> }

**Comment by SUPERCILEX** [comment]
I haven't looked at this repo in so long 😅. You'll need to add these lines before using any of the APIs (static initialization is recommended):
```
            System.setProperty(
                    "org.apache.poi.javax.xml.stream.XMLInputFactory",
                    "com.fasterxml.aalto.stax.InputFactoryImpl"
            )
            System.setProperty(
                    "org.apache.poi.javax.xml.stream.XMLOutputFactory",
                    "com.fasterxml.aalto.stax.OutputFactoryImpl"
            )
            System.setProperty(
                    "org.apache.poi.javax.xml.stream.XMLEventFactory",
                    "com.fasterxml.aalto.stax.EventFactoryImpl"
            )
```

**Comment by AhmadIzaz** [comment]
@SUPERCILEX  can you let us know where we have to add these lines System.setProperty.
In Gradle ??

**Comment by AhmadIzaz** [comment]
I have put these lines System.setProperty in Android Application class and this seems to be working with that yet.
