### ISSUE TITLE
Apply Color Style Issue

### ISSUE THREAD

**Issue by AnanlaTech** [SUPERCILEX/poi-android#6]
Applying color is not working. java.awt.Color class missing also I tried importing the java.awt.Color from other poi sample and used it did not work. I am new to android development. Can you please help me. I attached the color reference.
[Color.java.zip](https://github.com/SUPERCILEX/poi-android/files/3388618/Color.java.zip)

**Comment by SUPERCILEX** [comment]
Unfortunately, that's [not possible](https://stackoverflow.com/a/33210293/4548500) on Android. If you really wanted to, there's probably some hacky way to write your own version of java.awt.Color which delegates calls to android.graphics.Color, but I doubt that will work out nicely.
